coverage:
  precision: 2
  round: down
  range: "80...95"
  status:
    project:
      default:
        target: auto

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes

ignore:
  - "sc-kpm"
  - "sc-memory/sc-memory/utils/sc_console.cpp"
  - "sc-memory/sc-memory/utils/sc_message.cpp"
  - "thirdparty"
  - "*/tests/*"
